import time

algo = input('Digite algo:')
print('Aqui estão as informações sobre:')
time.sleep(1)
print('Tipo primitivo:', type(algo))
time.sleep(0.5)
print('È alphanumérico:',algo.isalnum())
time.sleep(0.5)
print('É alphabético:' , algo.isalpha())
time.sleep(0.5)
print('Tem somente "space":', algo.isspace())
time.sleep(0.5)
print('É número:', algo.isnumeric())
time.sleep(0.5)
print('Esta em maiusculo:', algo.isupper())
time.sleep(0.5)
print('Esta em minusculo:', algo.islower())
time.sleep(0.5)
print('Esta capitalizada:', algo.istitle())